#include <stdio.h>

//23-DETERMINE EL MENOR VALOR DE 5 NÚMEROS, INDICANDO ADEMÁS A QUÉ ORDEN 
//PERTENECE. CONSIDERE QUE EL MENOR VALOR PUEDE REPETIRSE. POR EJEMPLO: SI LOS 
//NÚMEROS INGRESADOS FUERAN: 14, 19, 14, 16, 15. LOS RESULTADOS DEBEN SER: EL 
//MENOR VALOR INGRESADO FUE 14 Y CORRESPONDEN AL PRIMER NÚMERO, TERCER 
//NÚMERO.

int main (){
	
	
	
	return 0;
}
